### ISSUE TITLE
Position is not updating

### ISSUE THREAD

**Issue by Araxion** [msdigital/oasis#16]
Hello, i am testing your app, but i have problem with auto update players positions - markers are not real time updating. You can find it on http://185.22.98.135:3000/. Thanks! :)

**Comment by msdigital** [comment]
Hi @Araxion 
That's a known issue, but unfortunately it's something i can not fix because its a server problem.
The issue lies within the server XML which doesn't always contain a player position (see image below).

![image](https://user-images.githubusercontent.com/9431791/183677777-e43ecc98-dceb-455f-a098-8fb88642bbdd.png)
